# Generated by Django 5.0 on 2024-02-20 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag_alter_article_options_scope_article_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Tags',
        ),
        migrations.CreateModel(
            name='CollectTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintag', models.BooleanField(default=False, verbose_name='основной')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_tags', to='articles.article')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_tags', to='articles.tags')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='article', through='articles.CollectTags', to='articles.tag'),
        ),
        migrations.DeleteModel(
            name='Scope',
        ),
    ]
